apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backendapihelm.fullname" . }}
  labels:
    {{- include "backendapihelm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backendapihelm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backendapihelm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backendapihelm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value|quote }}
            {{- end }}
              - name: EXTERNAL_INTGERATION_KEY
                valueFrom:
                  secretKeyRef:
                    name: external-integration-key
                    key: KEY
          ports:
            - name: http
              containerPort: {{ .Values.env.FLASK_RUN_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health_check
              port: http
          readinessProbe:
            httpGet:
              path: /health_check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

#### Health check container      
        - name: {{ .Chart.Name }}-health
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.healthtag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: log-volume
            mountPath: /var/log
          env:          
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value|quote }}
            {{- end }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - test -f /var/log/health_check.log
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - test -f /var/log/health_check.log
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            
      volumes:
      - name: log-volume
        emptyDir: {}
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
